spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/WebServiceDemo
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 9090

jwt:
  auth:
    converter:
      resource-id: myClients
      principle-attribute: preferred_username